# Generated by Django 4.2.2 on 2023-06-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_name'),
        ('containers', '0006_alter_container_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule', verbose_name='Расписание'),
        ),
    ]
