# Generated by Django 4.2.2 on 2023-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название порта назначения')),
                ('country', models.CharField(max_length=100, verbose_name='Страна порта назначения')),
                ('city', models.CharField(max_length=100, verbose_name='Город порта назначения')),
            ],
            options={
                'verbose_name': 'Порт назначения',
                'verbose_name_plural': 'Порты назначения',
            },
        ),
        migrations.CreateModel(
            name='DeparturePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название порта отправки')),
                ('country', models.CharField(max_length=100, verbose_name='Страна порта отправки')),
                ('city', models.CharField(max_length=100, verbose_name='Город порта отправки')),
            ],
            options={
                'verbose_name': 'Порт отправки',
                'verbose_name_plural': 'Порты отправки',
            },
        ),
    ]
