# Generated by Django 4.2.2 on 2023-06-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название маршрута')),
                ('distance', models.FloatField(verbose_name='Дистанция')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.arrivalport', verbose_name='Порт назначения')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.departureport', verbose_name='Порт отправки')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
    ]
