# Generated by Django 4.2.2 on 2023-06-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ships', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название расписания')),
                ('departure_date', models.DateField(verbose_name='Время отбытия')),
                ('arrival_date', models.DateField(verbose_name='Время прибытия')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route', verbose_name='Название маршрута')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.ship', verbose_name='Название судна')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
